#ifndef _BTEVALUATOR_H
#define _BTEVALUATOR_H

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "BehaviourTree.h"
#include "BehaviourTreeFactory.h"
#include <json.hpp>

namespace BT {
	class SpringCommand;


	/**
	 * This is the main entry point of the BtEvaluator module. It communicates with the Lua part and ticks the trees.
	 */
	class BtEvaluator {
		typedef std::map<std::string, BT::SpringCommand> CommandMap;
		typedef std::pair<BehaviourTree, BehaviourTree::EvaluationContext> Tree;
		typedef std::map<std::string, std::pair<BehaviourTree, BehaviourTree::EvaluationContext>> TreeMap;
	private:
		springai::OOAICallback* callback;
		springai::Game* game;
		springai::Lua* lua;

		int skirmishAIId;

		int nodeIdCounter;

		std::map<std::string, std::unique_ptr<const BehaviourTree::Node::Factory>> nodeFactories;

		BehaviourTree::EvaluationContext* reportingContext;
		TreeMap treeMap;
		
		void tickTree(Tree& tree);
		void update(int frame);
		
		void sendLuaMessage(const std::string& messageType) const;
		void sendLuaMessage(const std::string& messageType, const nlohmann::json& data) const;
		void receiveLuaMessage(const std::string&);
		void sendSuccessResponse() const;
		void sendFailureResponse(const std::string& error) const;

		void broadcastNodeDefinitions() const;
		std::unique_ptr<BehaviourTree::Node> createTreeFromJSON(const nlohmann::json& tree);
	public:
		explicit BtEvaluator(springai::OOAICallback* callback);

		~BtEvaluator() {}

		void Initialize();
		int HandleEvent(int topic, const void* data);

	};
}

#endif // _BTEVALUATOR_H

